name: Action-test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-ttt:
    name: 'test ${{ github.job }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check cmd
        if: github.event_name == 'push'
        run: mkdir artifact && echo test >> artifact/test.txt && echo ${{ github.job }} && echo GITHUB_JOB=${GITHUB_JOB}
      - name: Upload install file
        uses: actions/upload-artifact@v2
        with:
          name: upload-test
          path: artifact/