name: Action-test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check cmd
        run: ls -al
      - name: Upload install file
        uses: actions/upload-artifact@v2
        with:
          name: amazonlinux2
          path: web-dist/target/lena-work/